### PR TITLE
WIP Feature/fix intermittent ci errors

### PR DESCRIPTION
**Pull request by cryptomental**
@pelsasser please do not merge. This is a WIP PR to find the root cause for intermittent failures.

### CODE REVIEW

**Comment by cryptomental** [comment]
I will go up to 20, and if green I will simply update timeout to 180 sec + add dump of bridge logs in case it fails.

I am 99% certain that when it failed it was issue with Oraclize service, not with us.

**Comment by eswarasai** [comment]
@cryptomental -- Wondering if there isn't an easy way to setup and test the Travis CI env locally 🤔

**Comment by cryptomental** [comment]
@eswarasai there is - and actually I am using it all the time.

docker-compose up (run with foreground),
 then
docker-compose exec truffle npm install
docker-compose exec truffle-coverage npm install

and then e.g. coverage 
docker-compose exec eth-bridge-coverage scripts/wait_for_oraclize_connector.sh

works like a charm ;)

**Comment by cryptomental** [comment]
Boom. Issue reproduced. wait_for_oraclize_connector.sh exited with 1 even though connector was fine.
And the root cause is:

bridge restarts until ethereum node is initialized

In the example above it restarted 2 times:

```
eth-bridge_1           | Please wait...
eth-bridge_1           | [2018-05-17T09:28:53.948Z] WARN --dev mode active, contract myid checks and pending queries are skipped, use this only when testing, not in production
eth-bridge_1           | [2018-05-17T09:28:53.949Z] INFO you are running ethereum-bridge - version: 0.5.5
eth-bridge_1           | [2018-05-17T09:28:53.949Z] INFO saving logs to: ./bridge.log
eth-bridge_1           | [2018-05-17T09:28:53.950Z] INFO using active mode
eth-bridge_1           | [2018-05-17T09:28:53.950Z] INFO Connecting to eth node http://truffle:9545
eth-bridge_1           | [2018-05-17T09:28:55.348Z] ERROR http://truffle:9545 ethereum node not found, are you sure is it running?
eth-bridge_1           |  if you are using:
eth-bridge_1           |  * geth, append: --rpc --rpccorsdomain="*" --rpcaddr="truffle" --rpcport="9545"
eth-bridge_1           |  * parity, append: --geth --jsonrpc-hosts all --rpcaddr truffle --rpcport 9545 
eth-bridge_1           |  * ethereumjs-testrpc, try: testrpc -h truffle -p 9545
eth-bridge_1           | 
eth-bridge_1           | check also if your node or this machine is allowed to connect (firewall, port, etc..)
eth-bridge_1           | 
eth-bridge_1           | Exiting...
eth-bridge_1           | Please wait...
eth-bridge_1           | [2018-05-17T09:28:58.903Z] WARN --dev mode active, contract myid checks and pending queries are skipped, use this only when testing, not in production
eth-bridge_1           | [2018-05-17T09:28:58.904Z] INFO you are running ethereum-bridge - version: 0.5.5
eth-bridge_1           | [2018-05-17T09:28:58.904Z] INFO saving logs to: ./bridge.log
eth-bridge_1           | [2018-05-17T09:28:58.905Z] INFO using active mode
eth-bridge_1           | [2018-05-17T09:28:58.905Z] INFO Connecting to eth node http://truffle:9545
eth-bridge_1           | [2018-05-17T09:29:00.110Z] ERROR http://truffle:9545 ethereum node not found, are you sure is it running?
eth-bridge_1           |  if you are using:
eth-bridge_1           |  * geth, append: --rpc --rpccorsdomain="*" --rpcaddr="truffle" --rpcport="9545"
eth-bridge_1           |  * parity, append: --geth --jsonrpc-hosts all --rpcaddr truffle --rpcport 9545 
eth-bridge_1           |  * ethereumjs-testrpc, try: testrpc -h truffle -p 9545
eth-bridge_1           | 
eth-bridge_1           | check also if your node or this machine is allowed to connect (firewall, port, etc..)
eth-bridge_1           | 
eth-bridge_1           | Exiting...
eth-bridge_1           | Please wait...
eth-bridge_1           | [2018-05-17T09:29:02.712Z] WARN --dev mode active, contract myid checks and pending queries are skipped, use this only when testing, not in production
eth-bridge_1           | [2018-05-17T09:29:02.714Z] INFO you are running ethereum-bridge - version: 0.5.5
eth-bridge_1           | [2018-05-17T09:29:02.714Z] INFO saving logs to: ./bridge.log
eth-bridge_1           | [2018-05-17T09:29:02.715Z] INFO using active mode
eth-bridge_1           | [2018-05-17T09:29:02.715Z] INFO Connecting to eth node http://truffle:9545
eth-bridge_1           | [2018-05-17T09:29:04.367Z] INFO connected to node type EthereumJS TestRPC/v2.1.0-beta.7/ethereum-js
eth-bridge_1           | [2018-05-17T09:29:05.531Z] WARN Using 0x5aeda56215b167893e80b4fe645ba6d5bab767de to query contracts on your blockchain, make sure it is unlocked and do not use the same address to deploy your contracts
eth-bridge_1           | [2018-05-17T09:29:05.903Z] INFO deploying the oraclize connector contract...
eth-bridge_1           | [2018-05-17T09:29:16.929Z] INFO connector deployed to: 0xf7e3e47e06f1bddecb1b2f3a7f60b6b25fd2e233
eth-bridge_1           | [2018-05-17T09:29:17.355Z] INFO deploying the address resolver with a deterministic address...
eth-bridge_1           | [2018-05-17T09:29:40.177Z] INFO address resolver (OAR) deployed to: 0x6f485c8bf6fc43ea212e93bbf8ce046c7f1cb475
eth-bridge_1           | [2018-05-17T09:29:40.178Z] INFO updating connector pricing...
eth-bridge_1           | [2018-05-17T09:29:51.742Z] INFO successfully deployed all contracts
eth-bridge_1           | [2018-05-17T09:29:51.746Z] INFO instance configuration file saved to /ethereum-bridge/config/instance/oracle_instance_20180517T092951.json
eth-bridge_1           | 
eth-bridge_1           | Please add this line to your contract constructor:
eth-bridge_1           | 
eth-bridge_1           | OAR = OraclizeAddrResolverI(0x6f485C8BF6fc43eA212E93BBF8ce046C7f1cb475);
eth-bridge_1           | 
eth-bridge_1           | [2018-05-17T09:29:51.755Z] WARN re-org block listen is disabled
eth-bridge_1           | [2018-05-17T09:29:51.755Z] INFO Listening @ 0xf7e3e47e06f1bddecb1b2f3a7f60b6b25fd2e233 (Oraclize Connector)
eth-bridge_1           | 
eth-bridge_1           | (Ctrl+C to exit)
eth-bridge_1           | 
```

So the fix will be: wait for a while until truffle initialized, then run Oraclize connector container.

**Comment by cryptomental** [comment]
Fix proven to work on CI! I am closing this experimental PR and will open a proper one.

**Pull request closed without merging**
